### ISSUE TITLE
This is a copy of Gdbgui in violation of Gdbgui’s license 

### ISSUE THREAD

**Issue by cs01** [wilvk/pygdbcli#1]
You must, at the very least, include Gdbgui’s license text in the license of this project.

**Comment by wilvk** [comment]
Sorry about that. Will do.

**Comment by wilvk** [comment]
OK, done. Let me know if there's anything else I can do.

**Comment by wilvk** [comment]
FYI - I've decided not to use any gdbgui or pygdbmi code, so you can sleep easy. :)
